-- Generated by scripts/generate-season1-seed.mjs. Safe to run repeatedly in development.
-- Source: Firestore archive documents referenced by the supplied Season 1 HAR.
begin;

insert into public.leagues (id, name, slug, description) values ('ec653584-c2bf-3060-1bd3-c62ce33c6515'::uuid, 'Box Cricket League', 'box-cricket-league', null)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description;

insert into public.seasons (id, league_id, name, starts_on, ends_on, players_per_team) values ('8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'ec653584-c2bf-3060-1bd3-c62ce33c6515'::uuid, 'Season 1', null, null, 7)
on conflict (id) do update set
  league_id = excluded.league_id,
  name = excluded.name,
  starts_on = excluded.starts_on,
  ends_on = excluded.ends_on,
  players_per_team = excluded.players_per_team;

insert into public.seasons (id, league_id, name, starts_on, ends_on, players_per_team) values ('f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'ec653584-c2bf-3060-1bd3-c62ce33c6515'::uuid, 'Season 2', null, null, 9)
on conflict (id) do update set
  league_id = excluded.league_id,
  name = excluded.name,
  starts_on = excluded.starts_on,
  ends_on = excluded.ends_on,
  players_per_team = excluded.players_per_team;

with seed_teams (id, name, slug) as (values
  ('33ee5efe-d1b1-c4f8-acb3-ddcdbb4d417c'::uuid, 'Dhurandhars Revenge', 'dhurandhars-revenge'),
  ('27c1f2c3-e6c0-44e0-f09c-1961014578df'::uuid, 'Game Changers', 'game-changers'),
  ('e9096c6d-7abd-498e-5606-d86773e2efc1'::uuid, 'Jersey Indians', 'jersey-indians'),
  ('b78a30c1-286b-e8b4-1c1f-ec65b033fcd0'::uuid, 'Jersey Warriors', 'jersey-warriors'),
  ('43f275b1-daa6-27a9-e6ce-154211f99d69'::uuid, 'Power Strikers', 'power-strikers'),
  ('72e6d977-5489-abf1-30c8-eda70fa004cc'::uuid, 'Shadow Strikers', 'shadow-strikers'),
  ('185ca10b-db5a-9620-c7e9-dc8909190db2'::uuid, 'Short Pitch Sharks', 'short-pitch-sharks')
)
insert into public.teams (id, league_id, name, slug)
select id, 'ec653584-c2bf-3060-1bd3-c62ce33c6515'::uuid, name, slug from seed_teams
on conflict (id) do update set
  league_id = excluded.league_id,
  name = excluded.name,
  slug = excluded.slug;

with seed_teams_season2 (id, name, slug) as (values
  ('57a492aa-3a6f-4131-8d3a-7601cbcbfd64'::uuid, 'Dhurandhars United', 'dhurandhars-united'),
  ('233702c5-1b72-4306-bc75-568a92f4d514'::uuid, 'Indian Lions', 'indian-lions'),
  ('c787e828-ac30-4e7e-af79-327403aa10b7'::uuid, 'Titans', 'titans')
)
insert into public.teams (id, league_id, name, slug)
select id, 'ec653584-c2bf-3060-1bd3-c62ce33c6515'::uuid, name, slug from seed_teams_season2
on conflict (id) do update set
  league_id = excluded.league_id,
  name = excluded.name,
  slug = excluded.slug;

with seed_players (id, display_name) as (values
  ('f9bbbbb8-8e05-80f6-e038-57d7423eaefb'::uuid, 'Abhijeet Das'),
  ('c26bddb7-e9d7-b0ca-7f4f-e8885edc90b4'::uuid, 'Abhijeet Shete'),
  ('8dc0f614-0682-aff5-f0dd-420f37069659'::uuid, 'Abhishek Shrivastava'),
  ('686887d7-5850-fcd6-1dd2-ce48557580ee'::uuid, 'Amal Robinson Xavier'),
  ('95c057be-c118-1b13-69a2-20b10955e4cb'::uuid, 'Amit Dixit'),
  ('c90547ac-af96-598b-5a0e-e06261c553ff'::uuid, 'Ankit Vasa'),
  ('90e2f4da-542c-30bb-a785-9431e5c26f47'::uuid, 'Anshuman Karkare'),
  ('d1d9b80b-d970-5320-6ddf-525db3cbcf56'::uuid, 'Arihant Jain'),
  ('10a7700e-500a-4459-13c9-0ccc18c9f431'::uuid, 'Arup Dutta'),
  ('add689b8-4d9d-ac31-61db-4546be061eb7'::uuid, 'Asis Pahadsingh'),
  ('79aac98e-36d5-bdd1-6933-6c78defc724f'::uuid, 'Dipesh Salkar'),
  ('37aad006-2f0a-77d5-a3b0-495e345632c8'::uuid, 'Gokul J'),
  ('c77b1988-e19a-f6ff-5dcc-50b281c8c689'::uuid, 'Guru Nayak'),
  ('75ca707d-5558-9595-bad1-7418148112f4'::uuid, 'Hardik Shah'),
  ('1fbb76dd-d0ce-ff88-94ee-4fa8739cfbea'::uuid, 'Hari S'),
  ('b24f4f2f-5b71-0102-775a-2f09f6a33ae5'::uuid, 'Hitesh Chordia'),
  ('4bf4f240-f15c-bc84-2533-cf4f9c9d7cee'::uuid, 'Jai Mota'),
  ('421af43d-b60f-f96a-a234-ae356a421afe'::uuid, 'Karthik Subramanian'),
  ('728fd06d-d084-b333-98c6-1c0c81450848'::uuid, 'Kunal Gupta'),
  ('d0779b1a-0526-17e3-e053-7a90456c4479'::uuid, 'Mahendra Baroniya'),
  ('c96cdca1-9de2-e7dc-eb6f-0f187298517f'::uuid, 'Mahesh Kshatriya'),
  ('c318178b-7461-6191-bf68-63565590698b'::uuid, 'Manan Meghani'),
  ('9181e0a4-9a6a-2f82-b438-1c95d4072755'::uuid, 'Mandar Patki'),
  ('31ad46dd-302e-737d-ffff-92178695fafd'::uuid, 'Manish Doijode'),
  ('81fc3d1a-bd68-291c-1b14-0da436e64e65'::uuid, 'Navpreet Singh'),
  ('d263dd01-ab33-bb85-b203-446097384269'::uuid, 'Nikhil Jaiswal'),
  ('faa870eb-9567-cecc-f07f-c7f06f95434a'::uuid, 'Nitish Barya'),
  ('d6744517-eb40-b3ba-3039-b32d74267704'::uuid, 'Paras Adhiya'),
  ('48bd0420-c17a-e2f1-37d6-344055f729ba'::uuid, 'Prajwal Atreyas'),
  ('87f2e792-29cf-7c56-32d1-946291caaa1e'::uuid, 'Prashant Varma'),
  ('68a1e61a-341f-2061-73dd-74e27d156894'::uuid, 'Pratik Shah'),
  ('3566ceed-11c1-ec05-d3b4-cdbc8bd255ff'::uuid, 'Princely Gomes'),
  ('b8fd0ae6-d074-9cc2-b7d3-5cb1af3cf317'::uuid, 'Priyadarshan Mishra'),
  ('d53bf5d3-babd-5d0a-b506-fbcb435883f8'::uuid, 'Priyesh Agrawal'),
  ('0235b7be-05be-c032-1b07-e68fe46067aa'::uuid, 'Raghav Tatte'),
  ('14ff4627-93d1-203b-3f40-6dbcce1da0ef'::uuid, 'Raghu Gandrala'),
  ('87354cbc-237c-ccee-b1ec-9aa3d7afc7c4'::uuid, 'Raja Kondi'),
  ('68e36f93-b821-cfb6-6c4f-7f05be83eef7'::uuid, 'Sachin Karodkar'),
  ('51af5d5c-56c7-725c-6d6f-93f331886fc0'::uuid, 'Sagar Parmar'),
  ('04e44d1b-33ee-e873-7a25-b2042089ad31'::uuid, 'Saikat Bhaduri'),
  ('9be0aace-25c9-4044-ac9f-8107b743e234'::uuid, 'Samyak Dubey'),
  ('52aae18c-471c-7ab7-468b-37645d89c41a'::uuid, 'Sanjay Solanki'),
  ('fe0291ac-5531-0cce-a2b8-4a7c7c932aab'::uuid, 'Santosh Naidu'),
  ('11237ebb-0f46-782f-a61c-49ff277045a8'::uuid, 'Saravanan Veluchamy'),
  ('d7c3203c-845b-25c7-3b95-8c4a002b4dfd'::uuid, 'Sathish Dayalan'),
  ('52bd0ac8-9a82-acd1-9188-49297f346c69'::uuid, 'Satish Rojekar'),
  ('82565002-85c8-2a5c-01fa-359b6ef665fa'::uuid, 'Shouvik Biswas'),
  ('5c9ab724-89b2-4844-dc33-b0aa07b7bbb7'::uuid, 'Shreenath Kini'),
  ('b6c8af2b-c3cc-436e-ade7-b98a1d5299c7'::uuid, 'Shubham Neema'),
  ('fdb8a5b6-16b1-4f36-7f33-dbff254957c2'::uuid, 'Shubham Pandey'),
  ('db000b12-d892-4e07-a036-e1bb8aff4829'::uuid, 'Sital Kumar Pal'),
  ('a31c9262-b75d-1d6c-d136-71bdd14ee3f2'::uuid, 'Sonu Gupta'),
  ('c9ccf924-eb78-00bc-104f-9ec7bd61903d'::uuid, 'Srinibash Mohanty'),
  ('d6f96a62-9291-70de-7577-db91ff513bf5'::uuid, 'Sumit Gadgilwar'),
  ('5eb1f88f-455d-64c3-62b5-a28c00004ce0'::uuid, 'Sumit Lole'),
  ('fc9df8ed-efb1-a256-8083-13275a3b5e50'::uuid, 'Sundararajan Velayutham'),
  ('2d77801d-befd-ec3a-ac18-96e7ef45e116'::uuid, 'Supreeth Premkumar'),
  ('d1531624-e837-9759-e894-4224d6ea5623'::uuid, 'Suresh Thuthika'),
  ('8682a7c9-12f3-69b9-7478-98f4ce307298'::uuid, 'Sushant Gawali'),
  ('b955cca8-26c0-4967-4ecf-bfc4bc6e6abe'::uuid, 'Swapnil Shah'),
  ('f19a0e89-3c24-7dd5-e3a7-c5505b91cc3a'::uuid, 'Vihit Shah'),
  ('874d1f30-d029-5792-440f-07815eb3fe90'::uuid, 'Vishal P')
)
insert into public.players (id, display_name, full_name, created_by)
select id, display_name, null, null from seed_players
on conflict (id) do update set
  display_name = excluded.display_name,
  full_name = excluded.full_name;

with seed_players_season2 (id, display_name) as (values
  ('651b236c-f8d8-4dc4-9cf1-2b2160e4182e'::uuid, 'Amit Pandit'),
  ('c3e60feb-63f2-4026-b486-d9b855faa4c6'::uuid, 'Mayank Mishra'),
  ('8b89b16f-d8c7-401a-90ca-3d2705e06995'::uuid, 'Praveen Maddela'),
  ('2ea3dc87-df37-48e7-9ba4-a339784f2248'::uuid, 'Sanjay Patil'),
  ('53436aa5-c6ad-44b0-94eb-64e75bff623c'::uuid, 'Arun Varghese'),
  ('fbc87e96-0e8b-4ca9-8a9c-98f80aa88617'::uuid, 'Ashish Balsaraf'),
  ('3ce66644-6f59-4fd1-80c0-0a1175ec20cb'::uuid, 'Sarathi Mohan'),
  ('31ab3550-0057-4a24-ae55-c7a405b1995b'::uuid, 'Sathishkumar Ramaiyan'),
  ('e611993e-12e9-4e9a-87e3-70ac8abdd67d'::uuid, 'Naveen Amin'),
  ('e1acbc36-22b9-4bb5-bcd4-ea6c672255e4'::uuid, 'Rahul Gupta'),
  ('09cade46-27ed-49ab-a78d-356b3b32a516'::uuid, 'Yug Vajani'),
  ('710f0aa3-ea60-481b-9f76-403dde35df44'::uuid, 'Adarsh Chhajed'),
  ('79e57c4b-6920-4c39-b269-f8a05caffbed'::uuid, 'Amar Hete'),
  ('21d5620d-a499-4c15-9e7e-95b3b90daea5'::uuid, 'Cp Jain'),
  ('ec2c82c6-aa76-4dae-af75-8497cb55ae7f'::uuid, 'Jiteen Shinde'),
  ('69e46096-5c6f-44f3-967e-c02c593a9906'::uuid, 'Raj Kumar'),
  ('117b663a-b615-4b65-82cb-8712e1517afb'::uuid, 'Vicky P')
)
insert into public.players (id, display_name, full_name, created_by)
select id, display_name, null, null from seed_players_season2
on conflict (id) do update set
  display_name = excluded.display_name,
  full_name = excluded.full_name;

with seed_season_teams (id, season_id, team_id) as (values
  ('4bd11f07-ba3e-5d6a-e869-b59441446b5d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '33ee5efe-d1b1-c4f8-acb3-ddcdbb4d417c'::uuid),
  ('2000925f-e1c7-23d8-ad14-4d2685a23c92'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '27c1f2c3-e6c0-44e0-f09c-1961014578df'::uuid),
  ('dc7630dd-4d2c-eb63-4c10-f7b5ba1c72a5'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'e9096c6d-7abd-498e-5606-d86773e2efc1'::uuid),
  ('22a94330-e98b-6829-de2d-18f743a2b303'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'b78a30c1-286b-e8b4-1c1f-ec65b033fcd0'::uuid),
  ('eea3f7ec-736b-8852-15ac-48cc2652b57f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '43f275b1-daa6-27a9-e6ce-154211f99d69'::uuid),
  ('66637c85-7539-ee5b-243d-1a31aeade952'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '72e6d977-5489-abf1-30c8-eda70fa004cc'::uuid),
  ('10485b11-fd60-ab74-3929-e5d001cb65eb'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '185ca10b-db5a-9620-c7e9-dc8909190db2'::uuid)
)
insert into public.season_teams (id, season_id, team_id)
select id, season_id, team_id from seed_season_teams
on conflict (id) do update set
  season_id = excluded.season_id,
  team_id = excluded.team_id;

with seed_season_teams_season2 (id, season_id, team_id) as (values
  ('a0fe31a9-2622-47e3-ba8f-76c44906dd07'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '57a492aa-3a6f-4131-8d3a-7601cbcbfd64'::uuid),
  ('c55c2d46-8bcc-4def-ac46-6c50c0beb609'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '27c1f2c3-e6c0-44e0-f09c-1961014578df'::uuid),
  ('f007c3fc-a331-4a5a-ac49-49b137606db2'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '233702c5-1b72-4306-bc75-568a92f4d514'::uuid),
  ('993dbdf8-14d4-49da-bb8c-669a3f64e1cd'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'e9096c6d-7abd-498e-5606-d86773e2efc1'::uuid),
  ('b62863e8-a4aa-425c-a8f0-67ef89cc5dbf'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'b78a30c1-286b-e8b4-1c1f-ec65b033fcd0'::uuid),
  ('9d23ff79-0791-4c40-a2ff-3c8486779d8d'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '43f275b1-daa6-27a9-e6ce-154211f99d69'::uuid),
  ('8a76a183-168d-4ac6-90d3-ae143895852b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '72e6d977-5489-abf1-30c8-eda70fa004cc'::uuid),
  ('8a427ef3-ba9a-402f-9222-abe9caea7e91'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '185ca10b-db5a-9620-c7e9-dc8909190db2'::uuid),
  ('a14994fd-8d5b-40ea-bec1-af21d59fdd9b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'c787e828-ac30-4e7e-af79-327403aa10b7'::uuid)
)
insert into public.season_teams (id, season_id, team_id)
select id, season_id, team_id from seed_season_teams_season2
on conflict (id) do update set
  season_id = excluded.season_id,
  team_id = excluded.team_id;

with seed_season_rosters (id, season_team_id, season_id, player_id) as (values
  ('2e341f6e-9c41-26e2-3065-c289b1ad7b6d'::uuid, '4bd11f07-ba3e-5d6a-e869-b59441446b5d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'c318178b-7461-6191-bf68-63565590698b'::uuid),
  ('7a3b46d3-6731-5440-fb56-6f9f7f31f618'::uuid, '4bd11f07-ba3e-5d6a-e869-b59441446b5d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '686887d7-5850-fcd6-1dd2-ce48557580ee'::uuid),
  ('c2e03e81-314c-40c1-79d8-d22b305741fa'::uuid, '4bd11f07-ba3e-5d6a-e869-b59441446b5d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '68a1e61a-341f-2061-73dd-74e27d156894'::uuid),
  ('ef69f47b-5173-265f-2c78-bf5f5a044ef7'::uuid, '4bd11f07-ba3e-5d6a-e869-b59441446b5d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '87354cbc-237c-ccee-b1ec-9aa3d7afc7c4'::uuid),
  ('b8c4461f-6529-2e3b-e719-02df68270115'::uuid, '4bd11f07-ba3e-5d6a-e869-b59441446b5d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '10a7700e-500a-4459-13c9-0ccc18c9f431'::uuid),
  ('71533468-b2de-257e-3ec2-f73e62064453'::uuid, '4bd11f07-ba3e-5d6a-e869-b59441446b5d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '90e2f4da-542c-30bb-a785-9431e5c26f47'::uuid),
  ('e195fda0-8a71-0982-636c-4599a454c6c6'::uuid, '4bd11f07-ba3e-5d6a-e869-b59441446b5d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd1d9b80b-d970-5320-6ddf-525db3cbcf56'::uuid),
  ('20dbe1e5-5911-415d-5128-6667f480fdb2'::uuid, '2000925f-e1c7-23d8-ad14-4d2685a23c92'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '5eb1f88f-455d-64c3-62b5-a28c00004ce0'::uuid),
  ('90b701f3-e52a-9a03-7ca9-1ae4ddc1777a'::uuid, '2000925f-e1c7-23d8-ad14-4d2685a23c92'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '31ad46dd-302e-737d-ffff-92178695fafd'::uuid),
  ('bc748ce2-53b2-6aca-bb8c-9c7b2df0b637'::uuid, '2000925f-e1c7-23d8-ad14-4d2685a23c92'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '9be0aace-25c9-4044-ac9f-8107b743e234'::uuid),
  ('0223fb05-e952-c8d0-50fc-13220c79e54f'::uuid, '2000925f-e1c7-23d8-ad14-4d2685a23c92'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '728fd06d-d084-b333-98c6-1c0c81450848'::uuid),
  ('7dfba790-abe1-847a-bdc7-ae075100889a'::uuid, '2000925f-e1c7-23d8-ad14-4d2685a23c92'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'add689b8-4d9d-ac31-61db-4546be061eb7'::uuid),
  ('f0cf31b5-d6b3-417c-6bb8-86d14a8c7603'::uuid, '2000925f-e1c7-23d8-ad14-4d2685a23c92'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'b24f4f2f-5b71-0102-775a-2f09f6a33ae5'::uuid),
  ('7ee3b6eb-bc7d-4f0b-e951-da0dbde45bad'::uuid, '2000925f-e1c7-23d8-ad14-4d2685a23c92'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd7c3203c-845b-25c7-3b95-8c4a002b4dfd'::uuid),
  ('974b240b-47bd-e855-ca4c-6ccf830614ae'::uuid, 'dc7630dd-4d2c-eb63-4c10-f7b5ba1c72a5'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'b955cca8-26c0-4967-4ecf-bfc4bc6e6abe'::uuid),
  ('ebfb1df1-420d-6815-b599-857e8b297485'::uuid, 'dc7630dd-4d2c-eb63-4c10-f7b5ba1c72a5'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '48bd0420-c17a-e2f1-37d6-344055f729ba'::uuid),
  ('6ee28488-ed08-49cd-34e4-573650a83c8f'::uuid, 'dc7630dd-4d2c-eb63-4c10-f7b5ba1c72a5'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '87f2e792-29cf-7c56-32d1-946291caaa1e'::uuid),
  ('087a8167-e41f-f4b6-9935-c278a75ed00b'::uuid, 'dc7630dd-4d2c-eb63-4c10-f7b5ba1c72a5'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '81fc3d1a-bd68-291c-1b14-0da436e64e65'::uuid),
  ('ac995c9f-1321-7acc-fb7d-10f8ad07d77d'::uuid, 'dc7630dd-4d2c-eb63-4c10-f7b5ba1c72a5'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '1fbb76dd-d0ce-ff88-94ee-4fa8739cfbea'::uuid),
  ('f6cd5ad7-065b-2c1a-c2d0-e4a979fcf7db'::uuid, 'dc7630dd-4d2c-eb63-4c10-f7b5ba1c72a5'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'a31c9262-b75d-1d6c-d136-71bdd14ee3f2'::uuid),
  ('3805e9aa-bd47-3abe-443d-c489d7cc4a1b'::uuid, 'dc7630dd-4d2c-eb63-4c10-f7b5ba1c72a5'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'c96cdca1-9de2-e7dc-eb6f-0f187298517f'::uuid),
  ('e46a4a53-5bda-840f-6b03-155127e01f9b'::uuid, '22a94330-e98b-6829-de2d-18f743a2b303'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '3566ceed-11c1-ec05-d3b4-cdbc8bd255ff'::uuid),
  ('fc9371a4-28b4-e9f4-4ca3-ec254f7b6925'::uuid, '22a94330-e98b-6829-de2d-18f743a2b303'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '8dc0f614-0682-aff5-f0dd-420f37069659'::uuid),
  ('bb1e6686-1c64-85c0-0970-3b96c13cac1c'::uuid, '22a94330-e98b-6829-de2d-18f743a2b303'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '52aae18c-471c-7ab7-468b-37645d89c41a'::uuid),
  ('3ff3b026-4716-1cc5-83dd-1deea2451eaa'::uuid, '22a94330-e98b-6829-de2d-18f743a2b303'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'c90547ac-af96-598b-5a0e-e06261c553ff'::uuid),
  ('bf85092f-c731-b5be-ca3b-a622b44a95e9'::uuid, '22a94330-e98b-6829-de2d-18f743a2b303'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'b6c8af2b-c3cc-436e-ade7-b98a1d5299c7'::uuid),
  ('115420cb-1b71-a710-f7a0-3fb22e5e4982'::uuid, '22a94330-e98b-6829-de2d-18f743a2b303'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd6f96a62-9291-70de-7577-db91ff513bf5'::uuid),
  ('e75bfb25-aae7-bb51-1066-8e5315a6cf5a'::uuid, '22a94330-e98b-6829-de2d-18f743a2b303'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'b8fd0ae6-d074-9cc2-b7d3-5cb1af3cf317'::uuid),
  ('8cb11973-c213-b3b3-83b5-6e858eccb638'::uuid, 'eea3f7ec-736b-8852-15ac-48cc2652b57f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd263dd01-ab33-bb85-b203-446097384269'::uuid),
  ('673bc65c-4723-1fb8-202a-3438014fad02'::uuid, 'eea3f7ec-736b-8852-15ac-48cc2652b57f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '9181e0a4-9a6a-2f82-b438-1c95d4072755'::uuid),
  ('ca99f057-6939-bdda-23ab-82d91275e85c'::uuid, 'eea3f7ec-736b-8852-15ac-48cc2652b57f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '4bf4f240-f15c-bc84-2533-cf4f9c9d7cee'::uuid),
  ('5341fe5a-9e5c-1951-928e-ebc20696424e'::uuid, 'eea3f7ec-736b-8852-15ac-48cc2652b57f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '79aac98e-36d5-bdd1-6933-6c78defc724f'::uuid),
  ('27794936-03a4-da67-5084-d43465999817'::uuid, 'eea3f7ec-736b-8852-15ac-48cc2652b57f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'f9bbbbb8-8e05-80f6-e038-57d7423eaefb'::uuid),
  ('ec01343c-3262-6138-ae53-7040fda7c821'::uuid, 'eea3f7ec-736b-8852-15ac-48cc2652b57f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '82565002-85c8-2a5c-01fa-359b6ef665fa'::uuid),
  ('53dd86f3-67f1-dc7c-02a3-22e133877fdc'::uuid, 'eea3f7ec-736b-8852-15ac-48cc2652b57f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '95c057be-c118-1b13-69a2-20b10955e4cb'::uuid),
  ('f04db7d1-a1dc-bd54-6972-e62b4ddd48f2'::uuid, '66637c85-7539-ee5b-243d-1a31aeade952'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '5c9ab724-89b2-4844-dc33-b0aa07b7bbb7'::uuid),
  ('5f611791-f52e-6134-1518-2a9c7984da83'::uuid, '66637c85-7539-ee5b-243d-1a31aeade952'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'f19a0e89-3c24-7dd5-e3a7-c5505b91cc3a'::uuid),
  ('e7025cdc-b8e6-861b-236e-329ccaebbdcf'::uuid, '66637c85-7539-ee5b-243d-1a31aeade952'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '0235b7be-05be-c032-1b07-e68fe46067aa'::uuid),
  ('99ee2c28-51d1-5861-56c2-a57118eac3bc'::uuid, '66637c85-7539-ee5b-243d-1a31aeade952'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd6744517-eb40-b3ba-3039-b32d74267704'::uuid),
  ('daf0e719-aebc-6863-c65f-fce419fa9282'::uuid, '66637c85-7539-ee5b-243d-1a31aeade952'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd1531624-e837-9759-e894-4224d6ea5623'::uuid),
  ('221f1c8e-8ba5-2c5a-61dc-d626fe7ec937'::uuid, '66637c85-7539-ee5b-243d-1a31aeade952'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'c9ccf924-eb78-00bc-104f-9ec7bd61903d'::uuid),
  ('67940f27-69c6-165f-a322-7d2ef64fed42'::uuid, '66637c85-7539-ee5b-243d-1a31aeade952'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '37aad006-2f0a-77d5-a3b0-495e345632c8'::uuid),
  ('05d9ec72-a7a5-2d62-9151-dc60d49b933e'::uuid, '10485b11-fd60-ab74-3929-e5d001cb65eb'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd53bf5d3-babd-5d0a-b506-fbcb435883f8'::uuid),
  ('f57b221f-9b12-42da-841c-8b645254c4ec'::uuid, '10485b11-fd60-ab74-3929-e5d001cb65eb'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'fc9df8ed-efb1-a256-8083-13275a3b5e50'::uuid),
  ('8f03b882-148c-38ce-1241-03c3756452e5'::uuid, '10485b11-fd60-ab74-3929-e5d001cb65eb'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '14ff4627-93d1-203b-3f40-6dbcce1da0ef'::uuid),
  ('441c4f52-462b-0861-7410-110453be0735'::uuid, '10485b11-fd60-ab74-3929-e5d001cb65eb'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '2d77801d-befd-ec3a-ac18-96e7ef45e116'::uuid),
  ('90cfaff8-2bb2-074a-bc03-d41eb5f0d529'::uuid, '10485b11-fd60-ab74-3929-e5d001cb65eb'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'db000b12-d892-4e07-a036-e1bb8aff4829'::uuid),
  ('0e02be8f-06dc-9747-4577-afe9e8a9ca75'::uuid, '10485b11-fd60-ab74-3929-e5d001cb65eb'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'faa870eb-9567-cecc-f07f-c7f06f95434a'::uuid),
  ('ff1d849f-7b86-ed2a-a8c6-564d5c1a3f61'::uuid, '10485b11-fd60-ab74-3929-e5d001cb65eb'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '68e36f93-b821-cfb6-6c4f-7f05be83eef7'::uuid),
  ('e3faf6f0-8a6f-7be6-6083-8e548d90c18e'::uuid, '10485b11-fd60-ab74-3929-e5d001cb65eb'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '75ca707d-5558-9595-bad1-7418148112f4'::uuid),
  ('3394162b-867d-fe9b-5027-265e91246231'::uuid, 'dc7630dd-4d2c-eb63-4c10-f7b5ba1c72a5'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '8682a7c9-12f3-69b9-7478-98f4ce307298'::uuid),
  ('13d765a2-4e66-c0b2-7a25-07172874ea5b'::uuid, '4bd11f07-ba3e-5d6a-e869-b59441446b5d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'fdb8a5b6-16b1-4f36-7f33-dbff254957c2'::uuid),
  ('76b54eef-ccda-3b2e-7ea5-52dc352401f3'::uuid, '10485b11-fd60-ab74-3929-e5d001cb65eb'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '421af43d-b60f-f96a-a234-ae356a421afe'::uuid),
  ('12774891-2039-ccce-680a-41e64da3d748'::uuid, '22a94330-e98b-6829-de2d-18f743a2b303'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'fe0291ac-5531-0cce-a2b8-4a7c7c932aab'::uuid),
  ('ae39aef0-ba46-90c0-8a26-be4d4a4e1e74'::uuid, 'eea3f7ec-736b-8852-15ac-48cc2652b57f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'c77b1988-e19a-f6ff-5dcc-50b281c8c689'::uuid),
  ('bbd51786-6946-92f0-0d98-57c5c40bfdb5'::uuid, '2000925f-e1c7-23d8-ad14-4d2685a23c92'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '11237ebb-0f46-782f-a61c-49ff277045a8'::uuid),
  ('fb75048d-d013-e7ed-22df-bed1c19d78fb'::uuid, '22a94330-e98b-6829-de2d-18f743a2b303'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd0779b1a-0526-17e3-e053-7a90456c4479'::uuid),
  ('0bd18614-be53-f371-1622-f08c8c7c2e1a'::uuid, 'eea3f7ec-736b-8852-15ac-48cc2652b57f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '51af5d5c-56c7-725c-6d6f-93f331886fc0'::uuid),
  ('8ed73fa9-2f69-46f6-d691-a87ea2c4dcdd'::uuid, '66637c85-7539-ee5b-243d-1a31aeade952'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'c26bddb7-e9d7-b0ca-7f4f-e8885edc90b4'::uuid),
  ('d3a76619-f049-89f0-79f6-57aac23eaf0d'::uuid, '4bd11f07-ba3e-5d6a-e869-b59441446b5d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '04e44d1b-33ee-e873-7a25-b2042089ad31'::uuid),
  ('28000982-86a9-7426-fdeb-f141f36614a7'::uuid, '66637c85-7539-ee5b-243d-1a31aeade952'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '52bd0ac8-9a82-acd1-9188-49297f346c69'::uuid),
  ('aab70abd-5f67-d6a7-14c8-473b0a0f970b'::uuid, '2000925f-e1c7-23d8-ad14-4d2685a23c92'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '874d1f30-d029-5792-440f-07815eb3fe90'::uuid)
)
insert into public.season_rosters (id, season_team_id, season_id, player_id)
select id, season_team_id, season_id, player_id from seed_season_rosters
on conflict (id) do update set
  season_team_id = excluded.season_team_id,
  season_id = excluded.season_id,
  player_id = excluded.player_id;

with seed_season_rosters_season2 (id, season_team_id, season_id, player_id) as (values
  ('afd75887-d7a9-4c93-a052-b8b577d0b28d'::uuid, 'a0fe31a9-2622-47e3-ba8f-76c44906dd07'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'fdb8a5b6-16b1-4f36-7f33-dbff254957c2'::uuid),
  ('0f30356f-b8d0-4000-aa1f-b0bd1e7f85f3'::uuid, 'a0fe31a9-2622-47e3-ba8f-76c44906dd07'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '8dc0f614-0682-aff5-f0dd-420f37069659'::uuid),
  ('b3b40b29-594b-4dcf-8ad5-7eb7759d8096'::uuid, 'a0fe31a9-2622-47e3-ba8f-76c44906dd07'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '651b236c-f8d8-4dc4-9cf1-2b2160e4182e'::uuid),
  ('b1aa9b79-3a2c-4a6c-aaeb-31676b260d58'::uuid, 'a0fe31a9-2622-47e3-ba8f-76c44906dd07'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'c90547ac-af96-598b-5a0e-e06261c553ff'::uuid),
  ('319c1f78-1fe9-4269-9591-00144cf03253'::uuid, 'a0fe31a9-2622-47e3-ba8f-76c44906dd07'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'c3e60feb-63f2-4026-b486-d9b855faa4c6'::uuid),
  ('973f434e-9769-4d81-a529-22c48db7875d'::uuid, 'a0fe31a9-2622-47e3-ba8f-76c44906dd07'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '68a1e61a-341f-2061-73dd-74e27d156894'::uuid),
  ('b7819125-953d-4a2b-8aab-0d68ce90a7b4'::uuid, 'a0fe31a9-2622-47e3-ba8f-76c44906dd07'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '8b89b16f-d8c7-401a-90ca-3d2705e06995'::uuid),
  ('35491da2-852a-4931-bcb3-e98975a34483'::uuid, 'a0fe31a9-2622-47e3-ba8f-76c44906dd07'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '2ea3dc87-df37-48e7-9ba4-a339784f2248'::uuid),
  ('d7d6c3ff-244b-49ef-aa24-15ff3b9bf66f'::uuid, 'a0fe31a9-2622-47e3-ba8f-76c44906dd07'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'c9ccf924-eb78-00bc-104f-9ec7bd61903d'::uuid),
  ('918a932a-3007-44c3-8d09-75d7b558f4f4'::uuid, 'c55c2d46-8bcc-4def-ac46-6c50c0beb609'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '11237ebb-0f46-782f-a61c-49ff277045a8'::uuid),
  ('6b294b15-17ae-407a-b561-8109518152b5'::uuid, 'c55c2d46-8bcc-4def-ac46-6c50c0beb609'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '53436aa5-c6ad-44b0-94eb-64e75bff623c'::uuid),
  ('586fa3fe-7c9b-4f69-84f3-2c26d8549808'::uuid, 'c55c2d46-8bcc-4def-ac46-6c50c0beb609'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'fbc87e96-0e8b-4ca9-8a9c-98f80aa88617'::uuid),
  ('5f5b9e26-e8a7-4893-8277-1281ebbffb73'::uuid, 'c55c2d46-8bcc-4def-ac46-6c50c0beb609'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'add689b8-4d9d-ac31-61db-4546be061eb7'::uuid),
  ('84afeb53-6ff7-476f-aae5-99a39a1dd345'::uuid, 'c55c2d46-8bcc-4def-ac46-6c50c0beb609'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '87f2e792-29cf-7c56-32d1-946291caaa1e'::uuid),
  ('b4dc21c3-85c0-4be7-9a27-692e57749bc6'::uuid, 'c55c2d46-8bcc-4def-ac46-6c50c0beb609'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '87354cbc-237c-ccee-b1ec-9aa3d7afc7c4'::uuid),
  ('adeb0282-099e-4528-b30e-715c4afcecc1'::uuid, 'c55c2d46-8bcc-4def-ac46-6c50c0beb609'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'db000b12-d892-4e07-a036-e1bb8aff4829'::uuid),
  ('58aa5a62-6c6a-4481-9572-b86c69931821'::uuid, 'c55c2d46-8bcc-4def-ac46-6c50c0beb609'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'fc9df8ed-efb1-a256-8083-13275a3b5e50'::uuid),
  ('7f10302e-9862-4659-ace2-0d8d51ea823e'::uuid, 'c55c2d46-8bcc-4def-ac46-6c50c0beb609'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'f19a0e89-3c24-7dd5-e3a7-c5505b91cc3a'::uuid),
  ('749b996b-f516-45da-bd07-c7f5d886f412'::uuid, 'f007c3fc-a331-4a5a-ac49-49b137606db2'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'd0779b1a-0526-17e3-e053-7a90456c4479'::uuid),
  ('b61267c6-7c64-47e9-96d6-3490ea04e87f'::uuid, 'f007c3fc-a331-4a5a-ac49-49b137606db2'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '95c057be-c118-1b13-69a2-20b10955e4cb'::uuid),
  ('dcf9b7fd-c8bc-4ec4-af8a-2a920b50112b'::uuid, 'f007c3fc-a331-4a5a-ac49-49b137606db2'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '79aac98e-36d5-bdd1-6933-6c78defc724f'::uuid),
  ('8e796f07-7f91-49ff-82e5-cb7a98f2fb36'::uuid, 'f007c3fc-a331-4a5a-ac49-49b137606db2'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'd263dd01-ab33-bb85-b203-446097384269'::uuid),
  ('0795d527-3bed-4fe0-9471-27fb276a6b71'::uuid, 'f007c3fc-a331-4a5a-ac49-49b137606db2'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '48bd0420-c17a-e2f1-37d6-344055f729ba'::uuid),
  ('97a84e8b-0558-477b-abc8-8d551249b968'::uuid, 'f007c3fc-a331-4a5a-ac49-49b137606db2'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '3ce66644-6f59-4fd1-80c0-0a1175ec20cb'::uuid),
  ('2978410a-ad2b-4610-bcff-d0dedafc7d57'::uuid, 'f007c3fc-a331-4a5a-ac49-49b137606db2'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '31ab3550-0057-4a24-ae55-c7a405b1995b'::uuid),
  ('0de70777-6655-4b0d-9a94-60694a745e50'::uuid, 'f007c3fc-a331-4a5a-ac49-49b137606db2'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '52bd0ac8-9a82-acd1-9188-49297f346c69'::uuid),
  ('8be398ef-3a35-48c9-b390-37e61df51a4f'::uuid, '993dbdf8-14d4-49da-bb8c-669a3f64e1cd'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'b955cca8-26c0-4967-4ecf-bfc4bc6e6abe'::uuid),
  ('22e856ca-19b0-4745-ac54-1b1cdae648b9'::uuid, '993dbdf8-14d4-49da-bb8c-669a3f64e1cd'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'd1d9b80b-d970-5320-6ddf-525db3cbcf56'::uuid),
  ('c240224a-e2bc-4d83-a665-8504fda727d8'::uuid, '993dbdf8-14d4-49da-bb8c-669a3f64e1cd'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'e611993e-12e9-4e9a-87e3-70ac8abdd67d'::uuid),
  ('e97c8346-37f2-46c6-a4fa-78324a02f8ba'::uuid, '993dbdf8-14d4-49da-bb8c-669a3f64e1cd'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'faa870eb-9567-cecc-f07f-c7f06f95434a'::uuid),
  ('aefa9e12-a74f-4f55-b3a6-6593ad3c500c'::uuid, '993dbdf8-14d4-49da-bb8c-669a3f64e1cd'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '04e44d1b-33ee-e873-7a25-b2042089ad31'::uuid),
  ('542e7ceb-1185-4cf5-b3a0-47b34ffb7a67'::uuid, '993dbdf8-14d4-49da-bb8c-669a3f64e1cd'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '9be0aace-25c9-4044-ac9f-8107b743e234'::uuid),
  ('a65a161e-ed69-48e5-bd1a-3703f992172f'::uuid, '993dbdf8-14d4-49da-bb8c-669a3f64e1cd'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'a31c9262-b75d-1d6c-d136-71bdd14ee3f2'::uuid),
  ('d1b5f1be-626d-4836-83b2-46155fbb6693'::uuid, '993dbdf8-14d4-49da-bb8c-669a3f64e1cd'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'd6f96a62-9291-70de-7577-db91ff513bf5'::uuid),
  ('c029d381-4506-4d27-a65d-73951f1b9f78'::uuid, '993dbdf8-14d4-49da-bb8c-669a3f64e1cd'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '5eb1f88f-455d-64c3-62b5-a28c00004ce0'::uuid),
  ('f2cb9a9b-bc86-458c-8524-f75a3054fa86'::uuid, 'b62863e8-a4aa-425c-a8f0-67ef89cc5dbf'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '3566ceed-11c1-ec05-d3b4-cdbc8bd255ff'::uuid),
  ('87cef888-ae50-4b7c-9f60-092738bda7b5'::uuid, 'b62863e8-a4aa-425c-a8f0-67ef89cc5dbf'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'c77b1988-e19a-f6ff-5dcc-50b281c8c689'::uuid),
  ('91bb9139-8472-413c-a740-de4c2515928b'::uuid, 'b62863e8-a4aa-425c-a8f0-67ef89cc5dbf'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '1fbb76dd-d0ce-ff88-94ee-4fa8739cfbea'::uuid),
  ('7e52acef-ecfc-40d6-8276-43545acb251b'::uuid, 'b62863e8-a4aa-425c-a8f0-67ef89cc5dbf'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'b8fd0ae6-d074-9cc2-b7d3-5cb1af3cf317'::uuid),
  ('f461b86b-af04-41e4-b335-f4fae15ce02d'::uuid, 'b62863e8-a4aa-425c-a8f0-67ef89cc5dbf'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '68e36f93-b821-cfb6-6c4f-7f05be83eef7'::uuid),
  ('ad640f00-a5e1-4d8e-88d2-3e5318605240'::uuid, 'b62863e8-a4aa-425c-a8f0-67ef89cc5dbf'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'd1531624-e837-9759-e894-4224d6ea5623'::uuid),
  ('ab793b5b-8e54-4273-901c-b0f028959cfc'::uuid, 'b62863e8-a4aa-425c-a8f0-67ef89cc5dbf'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '8682a7c9-12f3-69b9-7478-98f4ce307298'::uuid),
  ('23878981-c60f-4451-823e-2e6d46c81677'::uuid, 'b62863e8-a4aa-425c-a8f0-67ef89cc5dbf'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '117b663a-b615-4b65-82cb-8712e1517afb'::uuid),
  ('d9b86746-bf53-4800-baef-a7d730012cb3'::uuid, '9d23ff79-0791-4c40-a2ff-3c8486779d8d'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'c96cdca1-9de2-e7dc-eb6f-0f187298517f'::uuid),
  ('f72a3786-093f-4743-a1d2-f5bbdc8a0627'::uuid, '9d23ff79-0791-4c40-a2ff-3c8486779d8d'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'f9bbbbb8-8e05-80f6-e038-57d7423eaefb'::uuid),
  ('48a81ea0-3e5c-49a0-9ef8-df0de6165a4e'::uuid, '9d23ff79-0791-4c40-a2ff-3c8486779d8d'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '686887d7-5850-fcd6-1dd2-ce48557580ee'::uuid),
  ('2a1954e5-014e-4b46-902b-4334152cf06d'::uuid, '9d23ff79-0791-4c40-a2ff-3c8486779d8d'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '90e2f4da-542c-30bb-a785-9431e5c26f47'::uuid),
  ('fb00ece2-1caf-43d0-b0d3-4fdcbd55aebc'::uuid, '9d23ff79-0791-4c40-a2ff-3c8486779d8d'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '37aad006-2f0a-77d5-a3b0-495e345632c8'::uuid),
  ('e5b4ab32-9d71-4bd7-8157-c6c96609d092'::uuid, '9d23ff79-0791-4c40-a2ff-3c8486779d8d'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '81fc3d1a-bd68-291c-1b14-0da436e64e65'::uuid),
  ('56989fc5-d4f6-4a0a-b8ae-ce7773643fda'::uuid, '9d23ff79-0791-4c40-a2ff-3c8486779d8d'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '52aae18c-471c-7ab7-468b-37645d89c41a'::uuid),
  ('79e4264e-d429-4ecf-8613-a9c54acc3382'::uuid, '9d23ff79-0791-4c40-a2ff-3c8486779d8d'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '82565002-85c8-2a5c-01fa-359b6ef665fa'::uuid),
  ('f3ad9aca-dc81-4c61-9c35-e2358f5f9d8f'::uuid, '9d23ff79-0791-4c40-a2ff-3c8486779d8d'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'b6c8af2b-c3cc-436e-ade7-b98a1d5299c7'::uuid),
  ('669d600e-0168-4147-81c4-1b16a5b9a2b1'::uuid, '8a76a183-168d-4ac6-90d3-ae143895852b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '5c9ab724-89b2-4844-dc33-b0aa07b7bbb7'::uuid),
  ('97f26e5d-53bb-454f-b5aa-a18c8058f9f3'::uuid, '8a76a183-168d-4ac6-90d3-ae143895852b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'c26bddb7-e9d7-b0ca-7f4f-e8885edc90b4'::uuid),
  ('a16524ba-1ac6-48ae-9011-56bf65af0adf'::uuid, '8a76a183-168d-4ac6-90d3-ae143895852b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '4bf4f240-f15c-bc84-2533-cf4f9c9d7cee'::uuid),
  ('d1cc97df-f729-4f2e-a02d-a0b564e4991b'::uuid, '8a76a183-168d-4ac6-90d3-ae143895852b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '728fd06d-d084-b333-98c6-1c0c81450848'::uuid),
  ('07bbdecf-9bbb-420b-b087-b5c380c7b56d'::uuid, '8a76a183-168d-4ac6-90d3-ae143895852b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '0235b7be-05be-c032-1b07-e68fe46067aa'::uuid),
  ('c86c06d3-3d82-492e-9940-73dcdb248a09'::uuid, '8a76a183-168d-4ac6-90d3-ae143895852b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'e1acbc36-22b9-4bb5-bcd4-ea6c672255e4'::uuid),
  ('2ce124da-7ec7-4dff-875b-a760570fe299'::uuid, '8a76a183-168d-4ac6-90d3-ae143895852b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'fe0291ac-5531-0cce-a2b8-4a7c7c932aab'::uuid),
  ('90b781bd-7151-487f-b009-c4f77c8dc31b'::uuid, '8a76a183-168d-4ac6-90d3-ae143895852b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '09cade46-27ed-49ab-a78d-356b3b32a516'::uuid),
  ('bceac77a-aa75-48b5-ac3d-97d16bba604b'::uuid, '8a427ef3-ba9a-402f-9222-abe9caea7e91'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '2d77801d-befd-ec3a-ac18-96e7ef45e116'::uuid),
  ('26e65f06-300a-4133-b088-5f82ca701be0'::uuid, '8a427ef3-ba9a-402f-9222-abe9caea7e91'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '710f0aa3-ea60-481b-9f76-403dde35df44'::uuid),
  ('b2f04020-b4ea-4c25-a885-b49fad647cd7'::uuid, '8a427ef3-ba9a-402f-9222-abe9caea7e91'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '79e57c4b-6920-4c39-b269-f8a05caffbed'::uuid),
  ('5807e739-9032-45b1-bf36-59e3def99e70'::uuid, '8a427ef3-ba9a-402f-9222-abe9caea7e91'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '10a7700e-500a-4459-13c9-0ccc18c9f431'::uuid),
  ('92ad098d-4e76-4eb7-9148-d3f2392d353a'::uuid, '8a427ef3-ba9a-402f-9222-abe9caea7e91'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '21d5620d-a499-4c15-9e7e-95b3b90daea5'::uuid),
  ('ad7d7089-6e9a-4fa1-88e6-29dc496851d0'::uuid, '8a427ef3-ba9a-402f-9222-abe9caea7e91'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '75ca707d-5558-9595-bad1-7418148112f4'::uuid),
  ('57aaa874-ece1-4ffa-9160-86c09b728949'::uuid, '8a427ef3-ba9a-402f-9222-abe9caea7e91'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'ec2c82c6-aa76-4dae-af75-8497cb55ae7f'::uuid),
  ('d0cb1c43-e575-4d7c-9e7c-b4186bfa7d3e'::uuid, '8a427ef3-ba9a-402f-9222-abe9caea7e91'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'c318178b-7461-6191-bf68-63565590698b'::uuid),
  ('2039ef96-f8de-4bec-8e71-13b1fcbb0c87'::uuid, '8a427ef3-ba9a-402f-9222-abe9caea7e91'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '9181e0a4-9a6a-2f82-b438-1c95d4072755'::uuid),
  ('6de96afd-7128-4484-a123-ca408f7ad00b'::uuid, 'a14994fd-8d5b-40ea-bec1-af21d59fdd9b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '31ad46dd-302e-737d-ffff-92178695fafd'::uuid),
  ('9b7fefcf-1d0f-4dac-89f9-38f583e55ffc'::uuid, 'a14994fd-8d5b-40ea-bec1-af21d59fdd9b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'b24f4f2f-5b71-0102-775a-2f09f6a33ae5'::uuid),
  ('616f3569-fa6b-4626-894f-48957280d94e'::uuid, 'a14994fd-8d5b-40ea-bec1-af21d59fdd9b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '421af43d-b60f-f96a-a234-ae356a421afe'::uuid),
  ('7342d4a5-1534-4b7d-8d12-69750d362e54'::uuid, 'a14994fd-8d5b-40ea-bec1-af21d59fdd9b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'd6744517-eb40-b3ba-3039-b32d74267704'::uuid),
  ('4726e2fd-df7b-42b9-91e2-935d78855efc'::uuid, 'a14994fd-8d5b-40ea-bec1-af21d59fdd9b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'd53bf5d3-babd-5d0a-b506-fbcb435883f8'::uuid),
  ('7aa09b14-757d-4b17-b803-998794176849'::uuid, 'a14994fd-8d5b-40ea-bec1-af21d59fdd9b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '69e46096-5c6f-44f3-967e-c02c593a9906'::uuid),
  ('9bc14199-4c81-4fc3-b279-94f8714d05c2'::uuid, 'a14994fd-8d5b-40ea-bec1-af21d59fdd9b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, '51af5d5c-56c7-725c-6d6f-93f331886fc0'::uuid),
  ('47ec4bba-2968-4e6e-9779-573150838d4a'::uuid, 'a14994fd-8d5b-40ea-bec1-af21d59fdd9b'::uuid, 'f5af40e3-953b-431e-93ba-233765ee02c0'::uuid, 'd7c3203c-845b-25c7-3b95-8c4a002b4dfd'::uuid)
)
insert into public.season_rosters (id, season_team_id, season_id, player_id)
select id, season_team_id, season_id, player_id from seed_season_rosters_season2
on conflict (id) do update set
  season_team_id = excluded.season_team_id,
  season_id = excluded.season_id,
  player_id = excluded.player_id;

with seed_season_team_managers (id, season_team_id, player_id, display_name) as (values
  ('5010d99c-4c38-510d-76ef-0cbb840ef9c5'::uuid, '4bd11f07-ba3e-5d6a-e869-b59441446b5d'::uuid, 'fdb8a5b6-16b1-4f36-7f33-dbff254957c2'::uuid, 'Shubham Pandey'),
  ('21d6b6f5-d848-12ee-e3b9-2d410c5dfbb9'::uuid, '2000925f-e1c7-23d8-ad14-4d2685a23c92'::uuid, '11237ebb-0f46-782f-a61c-49ff277045a8'::uuid, 'Saravanan Veluchamy'),
  ('1e5ab119-2f1f-47d6-ef6f-330322b7d1cf'::uuid, 'dc7630dd-4d2c-eb63-4c10-f7b5ba1c72a5'::uuid, '8682a7c9-12f3-69b9-7478-98f4ce307298'::uuid, 'Sushant Gawali'),
  ('c877207f-29d8-6600-7e9f-cd4a6b3da0e7'::uuid, '22a94330-e98b-6829-de2d-18f743a2b303'::uuid, 'fe0291ac-5531-0cce-a2b8-4a7c7c932aab'::uuid, 'Santosh Naidu'),
  ('2f284e0e-436e-7004-2fdc-0422ca1e96b9'::uuid, 'eea3f7ec-736b-8852-15ac-48cc2652b57f'::uuid, 'c77b1988-e19a-f6ff-5dcc-50b281c8c689'::uuid, 'Guru Nayak'),
  ('347e07b1-ac50-76f8-05e3-17436f636c3b'::uuid, '66637c85-7539-ee5b-243d-1a31aeade952'::uuid, '52bd0ac8-9a82-acd1-9188-49297f346c69'::uuid, 'Satish Rojekar'),
  ('9e3ae4d5-94f5-45a1-f041-929352bc1e22'::uuid, '10485b11-fd60-ab74-3929-e5d001cb65eb'::uuid, '75ca707d-5558-9595-bad1-7418148112f4'::uuid, 'Hardik Shah')
)
insert into public.season_team_managers (id, season_team_id, player_id, user_id, display_name)
select id, season_team_id, player_id, null, display_name from seed_season_team_managers
on conflict (id) do update set
  season_team_id = excluded.season_team_id,
  player_id = excluded.player_id,
  display_name = excluded.display_name;

with seed_season_team_managers_season2 (id, season_team_id, player_id, display_name) as (values
  ('255007b3-fc75-4f53-91a9-57796c214dfe'::uuid, 'a0fe31a9-2622-47e3-ba8f-76c44906dd07'::uuid, 'fdb8a5b6-16b1-4f36-7f33-dbff254957c2'::uuid, 'Shubham Pandey'),
  ('7cbc9647-e9b7-4300-b84a-0c082e030979'::uuid, 'c55c2d46-8bcc-4def-ac46-6c50c0beb609'::uuid, '11237ebb-0f46-782f-a61c-49ff277045a8'::uuid, 'Saravanan Veluchamy'),
  ('b4527f93-4c4d-43f8-94d7-e78b7b0cbf2d'::uuid, 'f007c3fc-a331-4a5a-ac49-49b137606db2'::uuid, 'd0779b1a-0526-17e3-e053-7a90456c4479'::uuid, 'Mahendra Baroniya'),
  ('7364f7fd-7c34-4159-8e94-b4c995cd86f6'::uuid, '993dbdf8-14d4-49da-bb8c-669a3f64e1cd'::uuid, 'b955cca8-26c0-4967-4ecf-bfc4bc6e6abe'::uuid, 'Swapnil Shah'),
  ('a876efb9-6bd2-4738-927e-0c638ce6d9c9'::uuid, 'b62863e8-a4aa-425c-a8f0-67ef89cc5dbf'::uuid, '3566ceed-11c1-ec05-d3b4-cdbc8bd255ff'::uuid, 'Princely Gomes'),
  ('d93af8cd-3743-4bd6-a6bb-f6f285cf1b00'::uuid, '9d23ff79-0791-4c40-a2ff-3c8486779d8d'::uuid, 'c96cdca1-9de2-e7dc-eb6f-0f187298517f'::uuid, 'Mahesh Kshatriya'),
  ('806a0ac4-45a4-477d-b329-ee7b8bfaec00'::uuid, '8a76a183-168d-4ac6-90d3-ae143895852b'::uuid, '5c9ab724-89b2-4844-dc33-b0aa07b7bbb7'::uuid, 'Shreenath Kini'),
  ('14295a3a-895f-4c5f-ba7f-d6ddad9ac2fb'::uuid, '8a427ef3-ba9a-402f-9222-abe9caea7e91'::uuid, '2d77801d-befd-ec3a-ac18-96e7ef45e116'::uuid, 'Supreeth Premkumar'),
  ('9d16cd94-7740-4375-9b0d-021231ce8921'::uuid, 'a14994fd-8d5b-40ea-bec1-af21d59fdd9b'::uuid, '31ad46dd-302e-737d-ffff-92178695fafd'::uuid, 'Manish Doijode')
)
insert into public.season_team_managers (id, season_team_id, player_id, user_id, display_name)
select id, season_team_id, player_id, null, display_name from seed_season_team_managers_season2
on conflict (id) do update set
  season_team_id = excluded.season_team_id,
  player_id = excluded.player_id,
  display_name = excluded.display_name;

with seed_legacy_stats (
  id,
  season_id,
  player_id,
  season_roster_id,
  source,
  source_player_id,
  source_team_name,
  matches_played,
  runs,
  balls_faced,
  fours,
  sixes,
  balls_bowled,
  runs_conceded,
  wickets,
  catches,
  stumpings,
  player_of_match_count,
  total_points,
  captured_at
) as (values
  ('1e3ef3da-d4d5-6a08-da85-4b11e982d930'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '75ca707d-5558-9595-bad1-7418148112f4'::uuid, 'e3faf6f0-8a6f-7be6-6083-8e548d90c18e'::uuid, 'firestore.archive.season1Leaderboard', '1oJxHrVpXts2YuOvc2b8', 'Short Pitch Sharks', 14, 216, 168, 12, 0, 84, 94, 10, 2, 0, 5, 434, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('537dd2be-bdc8-a6fe-fd74-82841b63ffa8'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'b955cca8-26c0-4967-4ecf-bfc4bc6e6abe'::uuid, '974b240b-47bd-e855-ca4c-6ccf830614ae'::uuid, 'firestore.archive.season1Leaderboard', '8ylzbIGyOIp0JaeC79Fs', 'Jersey Indians', 14, 169, 114, 15, 4, 84, 67, 6, 8, 0, 5, 388, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('9879a322-7694-6c84-7f23-cff9f5b546ea'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '52aae18c-471c-7ab7-468b-37645d89c41a'::uuid, 'bb1e6686-1c64-85c0-0970-3b96c13cac1c'::uuid, 'firestore.archive.season1Leaderboard', 'KFq0UX2GplZbCxXaLN0o', 'Jersey Warriors', 14, 137, 100, 16, 3, 90, 100, 11, 2, 0, 4, 356, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('c9c0485f-cac4-7bd0-c871-a64427ceb464'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '5c9ab724-89b2-4844-dc33-b0aa07b7bbb7'::uuid, 'f04db7d1-a1dc-bd54-6972-e62b4ddd48f2'::uuid, 'firestore.archive.season1Leaderboard', 'ynP5tOAGDXljRKBD234u', 'Shadow Strikers', 12, 113, 93, 11, 2, 72, 87, 9, 2, 0, 3, 279, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('9e4bf2f5-7a16-2047-b6e9-e6a0816ea67a'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '68a1e61a-341f-2061-73dd-74e27d156894'::uuid, 'c2e03e81-314c-40c1-79d8-d22b305741fa'::uuid, 'firestore.archive.season1Leaderboard', '6s6f41hUTTqYXCwQlF5z', 'Dhurandhars Revenge', 12, 120, 89, 12, 3, 68, 84, 7, 1, 0, 3, 264, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('01d4b3f4-1d8e-40c0-fa73-afebc56f3d25'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'c90547ac-af96-598b-5a0e-e06261c553ff'::uuid, '3ff3b026-4716-1cc5-83dd-1deea2451eaa'::uuid, 'firestore.archive.season1Leaderboard', 'NAnaTbhQjQ07oB8Py2sy', 'Jersey Warriors', 13, 110, 92, 7, 2, 81, 82, 4, 8, 0, 0, 254, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('ac540797-2e10-46a8-e540-33bd8e9d717b'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '8682a7c9-12f3-69b9-7478-98f4ce307298'::uuid, '3394162b-867d-fe9b-5027-265e91246231'::uuid, 'firestore.archive.season1Leaderboard', 'l709fTPrMaDGQ8Lhv1tG', 'Jersey Indians', 14, 94, 80, 5, 1, 84, 86, 11, 1, 0, 1, 251, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('473fe475-1158-591c-f601-47239acf48e4'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '79aac98e-36d5-bdd1-6933-6c78defc724f'::uuid, '5341fe5a-9e5c-1951-928e-ebc20696424e'::uuid, 'firestore.archive.season1Leaderboard', 'rmf1nSsoSOkiNqAEqh2c', 'Power Strikers', 11, 121, 89, 13, 2, 60, 74, 3, 2, 0, 2, 230, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('6f1a8451-6893-53c9-6d3f-dc210635e288'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'fdb8a5b6-16b1-4f36-7f33-dbff254957c2'::uuid, '13d765a2-4e66-c0b2-7a25-07172874ea5b'::uuid, 'firestore.archive.season1Leaderboard', 'bbA9C6LO5aG10xcMccgF', 'Dhurandhars Revenge', 13, 118, 100, 7, 3, 78, 103, 5, 1, 0, 2, 224, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('8bdc1588-91d8-a9da-de08-6ec5ee675f81'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '728fd06d-d084-b333-98c6-1c0c81450848'::uuid, '0223fb05-e952-c8d0-50fc-13220c79e54f'::uuid, 'firestore.archive.season1Leaderboard', 'KDGFoA7nTOk9xMLHZAeg', 'Game Changers', 12, 70, 71, 2, 1, 66, 71, 12, 0, 1, 0, 221, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('bf081d52-8de3-de1b-c459-5efe30f0d5ce'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '1fbb76dd-d0ce-ff88-94ee-4fa8739cfbea'::uuid, 'ac995c9f-1321-7acc-fb7d-10f8ad07d77d'::uuid, 'firestore.archive.season1Leaderboard', 'ABYZqiEFef3feve0d2Yi', 'Jersey Indians', 8, 60, 39, 3, 3, 47, 45, 10, 2, 1, 3, 211, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('f21cbe66-6d5c-85e2-49d2-0a8f6a869180'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '3566ceed-11c1-ec05-d3b4-cdbc8bd255ff'::uuid, 'e46a4a53-5bda-840f-6b03-155127e01f9b'::uuid, 'firestore.archive.season1Leaderboard', 'wSrlyU1CeD8t6UZTzYu5', 'Jersey Warriors', 10, 56, 64, 3, 0, 63, 72, 13, 2, 0, 0, 209, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('73022986-5257-adf9-0e07-263ff3ddaab9'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '87f2e792-29cf-7c56-32d1-946291caaa1e'::uuid, '6ee28488-ed08-49cd-34e4-573650a83c8f'::uuid, 'firestore.archive.season1Leaderboard', 'Y5s8qoLpRc9hwHDEb5GB', 'Jersey Indians', 14, 52, 57, 1, 1, 84, 82, 12, 0, 1, 1, 202, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('dc6139e6-78f5-6446-9468-52e5f479bc78'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '31ad46dd-302e-737d-ffff-92178695fafd'::uuid, '90b701f3-e52a-9a03-7ca9-1ae4ddc1777a'::uuid, 'firestore.archive.season1Leaderboard', 'JCJovNl17IkPX1wxMVVr', 'Game Changers', 12, 115, 101, 5, 2, 72, 97, 3, 2, 0, 1, 193, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('a09b657e-b4f5-0a64-e05a-a184aa0d3e6b'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'b6c8af2b-c3cc-436e-ade7-b98a1d5299c7'::uuid, 'bf85092f-c731-b5be-ca3b-a622b44a95e9'::uuid, 'firestore.archive.season1Leaderboard', 'xsn98pFnOmg0QGh8sTCi', 'Jersey Warriors', 10, 64, 56, 5, 0, 51, 62, 8, 1, 1, 0, 189, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('54476dc4-d13b-222f-94b8-9092afb4db4b'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '5eb1f88f-455d-64c3-62b5-a28c00004ce0'::uuid, '20dbe1e5-5911-415d-5128-6667f480fdb2'::uuid, 'firestore.archive.season1Leaderboard', 'hcKeoTNHtzXbboCKIRII', 'Game Changers', 12, 82, 77, 6, 0, 72, 74, 6, 2, 0, 2, 186, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('9ee2fa80-a52f-dd48-c2e2-fb0021af0723'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'c96cdca1-9de2-e7dc-eb6f-0f187298517f'::uuid, '3805e9aa-bd47-3abe-443d-c489d7cc4a1b'::uuid, 'firestore.archive.season1Leaderboard', 'WcAFWjDOY4kKqJr2iBDW', 'Jersey Indians', 14, 97, 80, 6, 1, 84, 93, 1, 7, 0, 2, 181, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('dea205c7-71c0-7be5-9879-d060bee8c32c'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '421af43d-b60f-f96a-a234-ae356a421afe'::uuid, '76b54eef-ccda-3b2e-7ea5-52dc352401f3'::uuid, 'firestore.archive.season1Leaderboard', 'BnV4f5een7nfNK5gsHrS', 'Short Pitch Sharks', 11, 29, 35, 1, 0, 66, 73, 11, 5, 0, 0, 171, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('0c395a53-0a09-ced5-0f34-1d69886ef665'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd263dd01-ab33-bb85-b203-446097384269'::uuid, '8cb11973-c213-b3b3-83b5-6e858eccb638'::uuid, 'firestore.archive.season1Leaderboard', 'ZKFsyAw2EInRxLofg7yk', 'Power Strikers', 12, 64, 70, 1, 2, 61, 74, 8, 2, 0, 1, 171, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('f687c74c-5878-b6f1-119e-765ab4792b22'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '2d77801d-befd-ec3a-ac18-96e7ef45e116'::uuid, '441c4f52-462b-0861-7410-110453be0735'::uuid, 'firestore.archive.season1Leaderboard', 'edLGTmQfFGZcK5JHj8ah', 'Short Pitch Sharks', 9, 29, 35, 2, 0, 54, 53, 10, 5, 0, 1, 171, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('5999da42-2b3f-067a-ce65-3cda1dd3bd96'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '686887d7-5850-fcd6-1dd2-ce48557580ee'::uuid, '7a3b46d3-6731-5440-fb56-6f9f7f31f618'::uuid, 'firestore.archive.season1Leaderboard', '3M2pKqQAhkNG3KktFa28', 'Dhurandhars Revenge', 11, 47, 54, 1, 0, 60, 68, 8, 4, 0, 0, 154, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('44f3ccaf-eba9-3b4a-b84f-cb14a6353a97'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'fe0291ac-5531-0cce-a2b8-4a7c7c932aab'::uuid, '12774891-2039-ccce-680a-41e64da3d748'::uuid, 'firestore.archive.season1Leaderboard', '7NX3RTBOnCiBjVGPYA5J', 'Jersey Warriors', 8, 53, 49, 1, 1, 42, 51, 8, 0, 0, 3, 153, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('ce51a60b-f4b4-dbab-8b75-87901618b00c'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'fc9df8ed-efb1-a256-8083-13275a3b5e50'::uuid, 'f57b221f-9b12-42da-841c-8b645254c4ec'::uuid, 'firestore.archive.season1Leaderboard', 'JTxSfIUUsHMrSql9r154', 'Short Pitch Sharks', 13, 63, 55, 3, 4, 72, 84, 5, 0, 0, 2, 152, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('c8bd8318-da93-fbc8-90b0-18fabd53161c'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '10a7700e-500a-4459-13c9-0ccc18c9f431'::uuid, 'b8c4461f-6529-2e3b-e719-02df68270115'::uuid, 'firestore.archive.season1Leaderboard', 'jjErwushEzDRR1lBISdx', 'Dhurandhars Revenge', 8, 55, 50, 0, 3, 48, 56, 3, 1, 1, 1, 133, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('600f8f77-9f73-c07c-ce5c-46020b34dffe'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '48bd0420-c17a-e2f1-37d6-344055f729ba'::uuid, 'ebfb1df1-420d-6815-b599-857e8b297485'::uuid, 'firestore.archive.season1Leaderboard', 'SqLtak2vHeLCJ7cKmJ9C', 'Jersey Indians', 10, 41, 47, 0, 0, 60, 68, 8, 1, 0, 0, 133, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('4fd7d40d-86a7-fffc-c570-0200d190f749'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'c77b1988-e19a-f6ff-5dcc-50b281c8c689'::uuid, 'ae39aef0-ba46-90c0-8a26-be4d4a4e1e74'::uuid, 'firestore.archive.season1Leaderboard', 'gjsyix9oD5MXgf6e6He2', 'Power Strikers', 11, 72, 73, 3, 0, 66, 102, 4, 1, 0, 0, 132, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('faf82adc-963c-406e-7761-b85603921df9'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd53bf5d3-babd-5d0a-b506-fbcb435883f8'::uuid, '05d9ec72-a7a5-2d62-9151-dc60d49b933e'::uuid, 'firestore.archive.season1Leaderboard', 'z9xVOnqceoNa93pN95F2', 'Short Pitch Sharks', 8, 31, 41, 1, 0, 44, 32, 6, 5, 0, 0, 131, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('0f5f7c52-6682-f456-1e38-73719d8cce85'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '11237ebb-0f46-782f-a61c-49ff277045a8'::uuid, 'bbd51786-6946-92f0-0d98-57c5c40bfdb5'::uuid, 'firestore.archive.season1Leaderboard', 'feRJXJdeTrbje4rZ8IRr', 'Game Changers', 12, 57, 67, 1, 1, 69, 81, 6, 0, 0, 1, 130, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('93a94d0e-7a21-8aeb-aaa7-cc67ee4e63ee'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd6744517-eb40-b3ba-3039-b32d74267704'::uuid, '99ee2c28-51d1-5861-56c2-a57118eac3bc'::uuid, 'firestore.archive.season1Leaderboard', 'AQdZsbca1sZI4W4vxnkK', 'Shadow Strikers', 10, 57, 66, 0, 0, 59, 80, 5, 4, 0, 0, 127, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('5904a7a2-8227-b2b5-44b8-2de869be494d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '0235b7be-05be-c032-1b07-e68fe46067aa'::uuid, 'e7025cdc-b8e6-861b-236e-329ccaebbdcf'::uuid, 'firestore.archive.season1Leaderboard', '9Qqzue8pM77V2VuWcfqh', 'Shadow Strikers', 8, 67, 60, 1, 2, 47, 58, 3, 0, 0, 0, 126, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('16eedf06-51b2-063f-2721-df0a1aee416e'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd0779b1a-0526-17e3-e053-7a90456c4479'::uuid, 'fb75048d-d013-e7ed-22df-bed1c19d78fb'::uuid, 'firestore.archive.season1Leaderboard', 'j7qNa1xI6plqoJaZS3xm', 'Jersey Warriors', 8, 44, 38, 2, 1, 48, 54, 6, 1, 0, 0, 124, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('b9b0b6fe-d5ae-99f0-1e08-d37c548afc1d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '68e36f93-b821-cfb6-6c4f-7f05be83eef7'::uuid, 'ff1d849f-7b86-ed2a-a8c6-564d5c1a3f61'::uuid, 'firestore.archive.season1Leaderboard', 'jfNL3TECHKOCxALhIg5K', 'Short Pitch Sharks', 11, 43, 56, 1, 1, 66, 78, 6, 1, 0, 0, 112, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('b854cada-a4f3-a3a1-f4fc-85287d0d95d0'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '51af5d5c-56c7-725c-6d6f-93f331886fc0'::uuid, '0bd18614-be53-f371-1622-f08c8c7c2e1a'::uuid, 'firestore.archive.season1Leaderboard', '6mP9p8uzpqppAjxOBpbo', 'Power Strikers', 7, 58, 45, 1, 2, 38, 52, 1, 0, 2, 1, 108, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('b8647c89-2571-510e-654b-b00a0efbe53d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '87354cbc-237c-ccee-b1ec-9aa3d7afc7c4'::uuid, 'ef69f47b-5173-265f-2c78-bf5f5a044ef7'::uuid, 'firestore.archive.season1Leaderboard', 'N8bHfsej87WzWvpAgjHt', 'Dhurandhars Revenge', 7, 29, 26, 3, 0, 41, 37, 6, 2, 0, 0, 108, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('9a89d9dc-1339-8d7d-67f4-6e46d0e228cf'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '82565002-85c8-2a5c-01fa-359b6ef665fa'::uuid, 'ec01343c-3262-6138-ae53-7040fda7c821'::uuid, 'firestore.archive.season1Leaderboard', 'pTpgnlml05cjQiFtHI9Y', 'Power Strikers', 6, 51, 39, 5, 0, 36, 46, 3, 1, 0, 0, 107, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('dcb4e253-a0f0-1cf9-b64e-74e61eaf9cd6'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '14ff4627-93d1-203b-3f40-6dbcce1da0ef'::uuid, '8f03b882-148c-38ce-1241-03c3756452e5'::uuid, 'firestore.archive.season1Leaderboard', 'pqZoMkW8B5Xemn0xg7Pv', 'Short Pitch Sharks', 8, 37, 41, 2, 0, 43, 40, 5, 1, 0, 0, 107, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('8613d6be-6617-54d0-510a-0bb2af853f18'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'f19a0e89-3c24-7dd5-e3a7-c5505b91cc3a'::uuid, '5f611791-f52e-6134-1518-2a9c7984da83'::uuid, 'firestore.archive.season1Leaderboard', 'uhyyhqCqgGqBdu0BYpZ4', 'Shadow Strikers', 8, 45, 52, 3, 0, 48, 70, 5, 0, 0, 0, 105, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('b4b2a798-5bf4-dc8e-8b49-35a3623f73ae'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '9181e0a4-9a6a-2f82-b438-1c95d4072755'::uuid, '673bc65c-4723-1fb8-202a-3438014fad02'::uuid, 'firestore.archive.season1Leaderboard', 'jnWZdBeTQvPQiAOF0i0h', 'Power Strikers', 8, 47, 49, 1, 1, 48, 57, 4, 0, 0, 1, 103, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('cbbce9bd-3eb0-64e1-58fa-1b8366db2f13'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'c26bddb7-e9d7-b0ca-7f4f-e8885edc90b4'::uuid, '8ed73fa9-2f69-46f6-d691-a87ea2c4dcdd'::uuid, 'firestore.archive.season1Leaderboard', 'sCsJJw1wA9oa73TvTHN9', 'Shadow Strikers', 4, 41, 33, 2, 2, 24, 28, 3, 2, 0, 0, 100, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('55253a35-e1fa-cb14-3d95-830977efac06'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '8dc0f614-0682-aff5-f0dd-420f37069659'::uuid, 'fc9371a4-28b4-e9f4-4ca3-ec254f7b6925'::uuid, 'firestore.archive.season1Leaderboard', 'Jm8CS559sIMe7p7pkEwr', 'Jersey Warriors', 8, 46, 40, 3, 0, 48, 61, 4, 0, 0, 0, 97, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('78b00d45-69c1-537b-7c34-073222c9a197'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd1d9b80b-d970-5320-6ddf-525db3cbcf56'::uuid, 'e195fda0-8a71-0982-636c-4599a454c6c6'::uuid, 'firestore.archive.season1Leaderboard', 'YXde1rydxYaJTp0TGt35', 'Dhurandhars Revenge', 7, 36, 43, 0, 1, 42, 47, 5, 1, 0, 0, 96, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('a4b0d698-7476-162b-0a52-0bb5f0a91001'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'db000b12-d892-4e07-a036-e1bb8aff4829'::uuid, '90cfaff8-2bb2-074a-bc03-d41eb5f0d529'::uuid, 'firestore.archive.season1Leaderboard', 'l2WZJ2np4cQNktVsikoO', 'Short Pitch Sharks', 8, 18, 34, 0, 0, 42, 57, 6, 0, 2, 0, 90, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('607afc1a-b0c4-438e-7a8d-4f10aaa2b8c9'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '04e44d1b-33ee-e873-7a25-b2042089ad31'::uuid, 'd3a76619-f049-89f0-79f6-57aac23eaf0d'::uuid, 'firestore.archive.season1Leaderboard', 'ogGcn3oUTFmQDEephlQJ', 'Dhurandhars Revenge', 8, 31, 37, 3, 0, 42, 62, 5, 2, 0, 0, 88, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('8e9d3c02-6bff-9be9-e807-b43dbdd37de2'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'a31c9262-b75d-1d6c-d136-71bdd14ee3f2'::uuid, 'f6cd5ad7-065b-2c1a-c2d0-e4a979fcf7db'::uuid, 'firestore.archive.season1Leaderboard', 'DFOS5uQaLLrGEonxhvDr', 'Jersey Indians', 3, 16, 16, 0, 1, 16, 22, 5, 1, 0, 0, 83, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('0e8adf7b-bb6b-674e-8a06-b88e8cfdb515'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd1531624-e837-9759-e894-4224d6ea5623'::uuid, 'daf0e719-aebc-6863-c65f-fce419fa9282'::uuid, 'firestore.archive.season1Leaderboard', 'J74I1jTS5WUi7KMcm1iV', 'Shadow Strikers', 10, 24, 42, 0, 0, 51, 80, 7, 0, 0, 0, 81, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('27d9440d-7544-fb86-1da1-8f73ea186fd5'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd6f96a62-9291-70de-7577-db91ff513bf5'::uuid, '115420cb-1b71-a710-f7a0-3fb22e5e4982'::uuid, 'firestore.archive.season1Leaderboard', 'u9bxtJDi7UZjLkffj7K8', 'Jersey Warriors', 8, 27, 34, 2, 0, 39, 52, 4, 0, 0, 0, 77, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('4c9c59fa-f300-01b8-0bf7-5e1702ed0923'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'd7c3203c-845b-25c7-3b95-8c4a002b4dfd'::uuid, '7ee3b6eb-bc7d-4f0b-e951-da0dbde45bad'::uuid, 'firestore.archive.season1Leaderboard', 'pfMKRUoWjVIC36WzJAeR', 'Game Changers', 6, 28, 34, 0, 1, 36, 57, 3, 2, 0, 0, 76, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('8aacb3ef-24f4-9cad-a581-39e117a7ca2f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '9be0aace-25c9-4044-ac9f-8107b743e234'::uuid, 'bc748ce2-53b2-6aca-bb8c-9c7b2df0b637'::uuid, 'firestore.archive.season1Leaderboard', 'x7oHpyBtdvlZVF9jGcne', 'Game Changers', 4, 21, 20, 1, 0, 24, 42, 6, 0, 0, 0, 76, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('c02adb3d-1f93-5d2a-04dc-19a322350451'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '81fc3d1a-bd68-291c-1b14-0da436e64e65'::uuid, '087a8167-e41f-f4b6-9935-c278a75ed00b'::uuid, 'firestore.archive.season1Leaderboard', 'Ba0bAWYCd5YHjwvyNmJB', 'Jersey Indians', 7, 19, 21, 0, 1, 42, 39, 5, 0, 0, 0, 72, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('82628150-cc48-925d-0c11-6b4551c805d1'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '52bd0ac8-9a82-acd1-9188-49297f346c69'::uuid, '28000982-86a9-7426-fdeb-f141f36614a7'::uuid, 'firestore.archive.season1Leaderboard', 'GvZHHoff7XBiEisbKMHJ', 'Shadow Strikers', 10, 34, 31, 6, 0, 60, 74, 4, 0, 0, 0, 71, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('cc69fc49-bfa3-4d87-0d19-5c0d0adca5d8'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '37aad006-2f0a-77d5-a3b0-495e345632c8'::uuid, '67940f27-69c6-165f-a322-7d2ef64fed42'::uuid, 'firestore.archive.season1Leaderboard', 'lwRAezBINTr75clBCVHT', 'Shadow Strikers', 9, 32, 39, 2, 0, 48, 62, 3, 0, 1, 0, 69, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('7870fe23-258f-094d-72cc-c45d3f44167c'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '4bf4f240-f15c-bc84-2533-cf4f9c9d7cee'::uuid, 'ca99f057-6939-bdda-23ab-82d91275e85c'::uuid, 'firestore.archive.season1Leaderboard', 'Yj19JrVBDARF2P6z342x', 'Power Strikers', 7, 17, 26, 0, 0, 42, 44, 3, 0, 2, 0, 68, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('892b8df7-4ce8-5d20-c211-5de56b6bff0e'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'add689b8-4d9d-ac31-61db-4546be061eb7'::uuid, '7dfba790-abe1-847a-bdc7-ae075100889a'::uuid, 'firestore.archive.season1Leaderboard', 'r0sZ0hDZ5Dm63RsOviT4', 'Game Changers', 8, 29, 36, 2, 0, 36, 43, 2, 1, 2, 0, 67, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('fbbf61d2-312d-594f-2b07-9347554f9e9f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '90e2f4da-542c-30bb-a785-9431e5c26f47'::uuid, '71533468-b2de-257e-3ec2-f73e62064453'::uuid, 'firestore.archive.season1Leaderboard', 'LNkbKpkBID8OBxdwOpHz', 'Dhurandhars Revenge', 9, 33, 41, 1, 1, 48, 83, 3, 0, 1, 0, 56, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('09979027-c069-fbf1-69e0-334ab99661d2'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'faa870eb-9567-cecc-f07f-c7f06f95434a'::uuid, '0e02be8f-06dc-9747-4577-afe9e8a9ca75'::uuid, 'firestore.archive.season1Leaderboard', '4OORvWptxMiU6BVc3Fi8', 'Short Pitch Sharks', 8, 31, 32, 1, 0, 48, 77, 1, 3, 1, 0, 50, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('43980c80-305e-e47f-2ed1-a6f50952ba6f'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'f9bbbbb8-8e05-80f6-e038-57d7423eaefb'::uuid, '27794936-03a4-da67-5084-d43465999817'::uuid, 'firestore.archive.season1Leaderboard', 'xuUmZFYUEVGbudjxwcyi', 'Power Strikers', 5, 14, 17, 0, 1, 29, 43, 3, 0, 1, 1, 49, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('1ad599b8-8a8f-55b7-43d6-5b67f1c29dee'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '95c057be-c118-1b13-69a2-20b10955e4cb'::uuid, '53dd86f3-67f1-dc7c-02a3-22e133877fdc'::uuid, 'firestore.archive.season1Leaderboard', 'f6cO5jsnE96aQTfu7kh2', 'Power Strikers', 5, 15, 18, 2, 0, 30, 45, 2, 0, 0, 0, 31, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('052eab7b-47c3-17ac-8f64-d5fa088185d7'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'c318178b-7461-6191-bf68-63565590698b'::uuid, '2e341f6e-9c41-26e2-3065-c289b1ad7b6d'::uuid, 'firestore.archive.season1Leaderboard', 'uN9qgqOT6pR43o4gmGEM', 'Dhurandhars Revenge', 3, 1, 6, 0, 0, 18, 23, 2, 0, 1, 0, 23, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('5ea22d5c-2b8e-7c36-6ea5-d24cd0756895'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'c9ccf924-eb78-00bc-104f-9ec7bd61903d'::uuid, '221f1c8e-8ba5-2c5a-61dc-d626fe7ec937'::uuid, 'firestore.archive.season1Leaderboard', 'S9XLNTQt3GXOHN5YjXOa', 'Shadow Strikers', 1, 6, 6, 0, 0, 6, 5, 0, 0, 1, 0, 16, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('90fb6a16-28dd-ce70-6afa-ac2a8e0dce0d'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'b24f4f2f-5b71-0102-775a-2f09f6a33ae5'::uuid, 'f0cf31b5-d6b3-417c-6bb8-86d14a8c7603'::uuid, 'firestore.archive.season1Leaderboard', '1B3zqQnbF3wlEYT5ASVQ', 'Game Changers', 3, 8, 16, 0, 0, 16, 23, 1, 0, 0, 0, 12, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('7398b84b-3867-d68e-cb15-af273d32a825'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, '874d1f30-d029-5792-440f-07815eb3fe90'::uuid, 'aab70abd-5f67-d6a7-14c8-473b0a0f970b'::uuid, 'firestore.archive.season1Leaderboard', 'cTCTtiNBvq3bZcKCKJPZ', 'Game Changers', 3, 6, 9, 0, 0, 12, 25, 0, 0, 1, 0, 9, '2026-07-25T17:47:15.359Z'::timestamptz),
  ('76ec140f-e75f-af52-9762-d52262ba89d1'::uuid, '8ede60fe-84df-49f1-53aa-b261d5671db2'::uuid, 'b8fd0ae6-d074-9cc2-b7d3-5cb1af3cf317'::uuid, 'e75bfb25-aae7-bb51-1066-8e5315a6cf5a'::uuid, 'firestore.archive.season1Leaderboard.missing-defaulted', 'x9QI3wXgc19N86BtTj5V', 'Jersey Warriors', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '2026-07-25T17:47:15.359Z'::timestamptz)
)
insert into public.legacy_season_player_stats (
  id, season_id, player_id, season_roster_id, source, source_player_id, source_team_name,
  matches_played, runs, balls_faced, fours, sixes, balls_bowled, runs_conceded,
  wickets, catches, stumpings, player_of_match_count, total_points, captured_at
)
select * from seed_legacy_stats
on conflict (season_id, source, source_player_id) do update set
  player_id = excluded.player_id,
  season_roster_id = excluded.season_roster_id,
  source_team_name = excluded.source_team_name,
  matches_played = excluded.matches_played,
  runs = excluded.runs,
  balls_faced = excluded.balls_faced,
  fours = excluded.fours,
  sixes = excluded.sixes,
  balls_bowled = excluded.balls_bowled,
  runs_conceded = excluded.runs_conceded,
  wickets = excluded.wickets,
  catches = excluded.catches,
  stumpings = excluded.stumpings,
  player_of_match_count = excluded.player_of_match_count,
  total_points = excluded.total_points,
  captured_at = excluded.captured_at;

commit;
